/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjava;

import com.sun.java.swing.plaf.motif.MotifDesktopPaneUI;
import com.sun.java.swing.plaf.windows.WindowsDesktopPaneUI;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.plaf.basic.BasicDesktopPaneUI;
import javax.swing.plaf.multi.MultiDesktopPaneUI;
import javax.swing.plaf.synth.SynthDesktopPaneUI;

/**
 *
 * @author DELL
 */
public class frmReport extends javax.swing.JFrame {

    /**
     * Creates new form frmReport
     */
    public frmReport() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        //jDesktopPane1.setUI(new MotifDesktopPaneUI());
//    JRDataSource dataSource = null;
//
//        Map parameters = new HashMap();
//    parameters.put("id", 42);
//
//    JasperReport report = (JasperReport) 
//            JRLoader.loadObject("c:/reports/report.jasper");
//
//    JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, dataSource);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        dlgLogin = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnManage = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        infLogin.setClosable(true);
        infLogin.setVisible(true);
        infLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        infLogin.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jTextField1.setText("jTextField1");
        infLogin.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 340, -1));

        jPasswordField1.setText("jPasswordField1");
        infLogin.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 340, -1));

        infLogin.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        dlgLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgLogin.setMaximumSize(new java.awt.Dimension(570, 334));
        dlgLogin.setMinimumSize(new java.awt.Dimension(570, 334));
        dlgLogin.setModal(true);
        dlgLogin.setResizable(false);

        javax.swing.GroupLayout dlgLoginLayout = new javax.swing.GroupLayout(dlgLogin.getContentPane());
        dlgLogin.getContentPane().setLayout(dlgLoginLayout);
        dlgLoginLayout.setHorizontalGroup(
            dlgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        dlgLoginLayout.setVerticalGroup(
            dlgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Phetsarath OT", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/ic-logo.png"))); // NOI18N
        jMenu1.setText("CS Bank");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 30));
        jMenuBar1.add(jMenu1);

        mnManage.setBorder(null);
        mnManage.setText("Manager");
        mnManage.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        mnManage.setMargin(new java.awt.Insets(0, 0, 0, 10));

        jMenu3.setText("Address");

        jMenuItem1.setText("Province");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("District");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        mnManage.add(jMenu3);

        jMenuBar1.add(mnManage);

        jMenu4.setBorder(null);
        jMenu4.setText("Services");
        jMenu4.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 10));
        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(null);
        jMenu5.setText("Report");
        jMenu5.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 10));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
            infTest test = new infTest();
            test.setVisible(true);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize = test.getSize();
            test.setLocation((desktopSize.width - jInternalFrameSize.width)/2, (desktopSize.height- jInternalFrameSize.height)/2);
            jDesktopPane1.add(test);
           selectLastOpenedInternalFrame();
        try {
            test.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            infDistrict district = new infDistrict();
            district.setVisible(true);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize = district.getSize();
            district.setLocation((desktopSize.width - jInternalFrameSize.width)/2, (desktopSize.height- jInternalFrameSize.height)/2);
            jDesktopPane1.add(district);
           selectLastOpenedInternalFrame();
        try {
            district.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
       
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        
        dlgLogin.show(true);
       // infLogin.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgLogin;
    private javax.swing.JInternalFrame infLogin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu mnManage;
    // End of variables declaration//GEN-END:variables

    private void selectLastOpenedInternalFrame() {
             jDesktopPane1.getDesktopManager().activateFrame((jDesktopPane1.getAllFrames()[jDesktopPane1.getAllFrames().length-1]));
            jDesktopPane1.setSelectedFrame(jDesktopPane1.getAllFrames()[jDesktopPane1.getAllFrames().length-1]);
//            try {
//                jDesktopPane1.getAllFrames()[jDesktopPane1.getAllFrames().length-1].setSelected(true);
////                if(jDesktopPane1.getAllFrames().length > 1){
////                    jDesktopPane1.getAllFrames()[jDesktopPane1.getAllFrames().length-2].setSelected(false);
////                }
//            } catch (PropertyVetoException ex) {
//                Logger.getLogger(frmReport.class.getName()).log(Level.SEVERE, null, ex);
//            }
    }
}
